### ISSUE TITLE
Installation error for rasa-webchat

### ISSUE THREAD

**Issue by swagat123** [botfront/rasa-webchat#27]
Hi I tried to install rasa-webachat  , please find the below error details 

```
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > node-sass@4.10.0 install /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep Cached binary found at /home/ec2-user/.npm/node-sass/4.10.0/linux-x64-57_binding.node
npm ERR! prepareGitDep
npm ERR! prepareGitDep > node-sass@4.10.0 postinstall /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/node-sass
npm ERR! prepareGitDep > node scripts/build.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep Binary found at /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/node-sass/vendor/linux-x64-57/binding.node
npm ERR! prepareGitDep Testing binary
npm ERR! prepareGitDep Binary is fine
npm ERR! prepareGitDep
npm ERR! prepareGitDep > rasa-webchat@0.4.1 prepare /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f
npm ERR! prepareGitDep > npm run build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > rasa-webchat@0.4.1 build /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f
npm ERR! prepareGitDep > webpack-cli --config webpack.prod.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! prepareGitDep npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! prepareGitDep npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! prepareGitDep /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/config-yargs.js:89
npm ERR! prepareGitDep                          describe: optionsSchema.definitions.output.properties.path.description,
npm ERR! prepareGitDep                                                                     ^
npm ERR! prepareGitDep
npm ERR! prepareGitDep TypeError: Cannot read property 'properties' of undefined
npm ERR! prepareGitDep     at module.exports (/home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/config-yargs.js:89:48)
npm ERR! prepareGitDep     at /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/webpack.js:60:27
npm ERR! prepareGitDep     at Object.<anonymous> (/home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/webpack.js:515:3)
npm ERR! prepareGitDep     at Module._compile (module.js:653:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (module.js:664:10)
npm ERR! prepareGitDep     at Module.load (module.js:566:32)
npm ERR! prepareGitDep     at tryModuleLoad (module.js:506:12)
npm ERR! prepareGitDep     at Function.Module._load (module.js:498:3)
npm ERR! prepareGitDep     at Function.Module.runMain (module.js:694:10)
npm ERR! prepareGitDep     at startup (bootstrap_node.js:204:16)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! rasa-webchat@0.4.1 build: `webpack-cli --config webpack.prod.js`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the rasa-webchat@0.4.1 build script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/ec2-user/.npm/_logs/2018-12-03T06_31_26_817Z-debug.log
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! rasa-webchat@0.4.1 prepare: `npm run build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the rasa-webchat@0.4.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/ec2-user/.npm/_logs/2018-12-03T06_31_27_051Z-debug.log
npm ERR! prepareGitDep
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:mrbot-ai/rasa-webchat.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-12-03T06_31_27_196Z-debug.log


[ec2-user@ip-10-0-0-4 node_modules]$ cat /home/ec2-user/.npm/_logs/2018-12-03T06_31_27_196Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'mrbot-ai/rasa-webchat' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose config Skipping project config: /home/ec2-user/.npmrc. (matches userconfig)
5 verbose npm-session 6f4e287f482cd2f8
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 verbose prepareGitDep undefined: installing devDeps and running prepare script.
9 error prepareGitDep 1>
9 error prepareGitDep > node-sass@4.10.0 install /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/node-sass
9 error prepareGitDep > node scripts/install.js
9 error prepareGitDep
9 error prepareGitDep Cached binary found at /home/ec2-user/.npm/node-sass/4.10.0/linux-x64-57_binding.node
9 error prepareGitDep
9 error prepareGitDep > node-sass@4.10.0 postinstall /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/node-sass
9 error prepareGitDep > node scripts/build.js
9 error prepareGitDep
9 error prepareGitDep Binary found at /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/node-sass/vendor/linux-x64-57/binding.node
9 error prepareGitDep Testing binary
9 error prepareGitDep Binary is fine
9 error prepareGitDep
9 error prepareGitDep > rasa-webchat@0.4.1 prepare /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f
9 error prepareGitDep > npm run build
9 error prepareGitDep
9 error prepareGitDep
9 error prepareGitDep > rasa-webchat@0.4.1 build /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f
9 error prepareGitDep > webpack-cli --config webpack.prod.js
10 error prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
10 error prepareGitDep npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
10 error prepareGitDep npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
10 error prepareGitDep npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
10 error prepareGitDep npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
10 error prepareGitDep /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/config-yargs.js:89
10 error prepareGitDep                          describe: optionsSchema.definitions.output.properties.path.description,
10 error prepareGitDep                                                                     ^
10 error prepareGitDep
10 error prepareGitDep TypeError: Cannot read property 'properties' of undefined
10 error prepareGitDep     at module.exports (/home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/config-yargs.js:89:48)
10 error prepareGitDep     at /home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/webpack.js:60:27
10 error prepareGitDep     at Object.<anonymous> (/home/ec2-user/.npm/_cacache/tmp/git-clone-b486576f/node_modules/webpack-cli/bin/webpack.js:515:3)
10 error prepareGitDep     at Module._compile (module.js:653:30)
10 error prepareGitDep     at Object.Module._extensions..js (module.js:664:10)
10 error prepareGitDep     at Module.load (module.js:566:32)
10 error prepareGitDep     at tryModuleLoad (module.js:506:12)
10 error prepareGitDep     at Function.Module._load (module.js:498:3)
10 error prepareGitDep     at Function.Module.runMain (module.js:694:10)
10 error prepareGitDep     at startup (bootstrap_node.js:204:16)
10 error prepareGitDep npm ERR! code ELIFECYCLE
10 error prepareGitDep npm ERR! errno 1
10 error prepareGitDep npm ERR! rasa-webchat@0.4.1 build: `webpack-cli --config webpack.prod.js`
10 error prepareGitDep npm ERR! Exit status 1
10 error prepareGitDep npm ERR!
10 error prepareGitDep npm ERR! Failed at the rasa-webchat@0.4.1 build script.
10 error prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10 error prepareGitDep
10 error prepareGitDep npm ERR! A complete log of this run can be found in:
10 error prepareGitDep npm ERR!     /home/ec2-user/.npm/_logs/2018-12-03T06_31_26_817Z-debug.log
10 error prepareGitDep npm ERR! code ELIFECYCLE
10 error prepareGitDep npm ERR! errno 1
10 error prepareGitDep npm ERR! rasa-webchat@0.4.1 prepare: `npm run build`
10 error prepareGitDep npm ERR! Exit status 1
10 error prepareGitDep npm ERR!
10 error prepareGitDep npm ERR! Failed at the rasa-webchat@0.4.1 prepare script.
10 error prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10 error prepareGitDep
10 error prepareGitDep npm ERR! A complete log of this run can be found in:
10 error prepareGitDep npm ERR!     /home/ec2-user/.npm/_logs/2018-12-03T06_31_27_051Z-debug.log
11 silly fetchPackageMetaData error for github:mrbot-ai/rasa-webchat Non-registry package missing package.json: github:mrbot-ai/rasa-webchat.
12 timing stage:rollbackFailedOptional Completed in 1ms
13 timing stage:runTopLevelLifecycles Completed in 43704ms
14 verbose stack Error: Non-registry package missing package.json: github:mrbot-ai/rasa-webchat.
14 verbose stack     at BB.join (/usr/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:162:23)
14 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
14 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
14 verbose stack     at Promise.eval (eval at thenCallback (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
14 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
14 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
14 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21)
14 verbose stack     at emitNone (events.js:111:20)
14 verbose stack     at Object.emit (events.js:208:7)
14 verbose stack     at Object.Parser.on._ (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:75:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at Object.emit (events.js:214:7)
14 verbose stack     at Object.[emit] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:229:12)
15 verbose cwd /home/ec2-user/node_modules
16 verbose Linux 3.10.0-862.14.4.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "mrbot-ai/rasa-webchat"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ENOPACKAGEJSON
21 error package.json Non-registry package missing package.json: github:mrbot-ai/rasa-webchat.
22 error package.json npm can't find a package.json file in your current directory.
23 verbose exit [ 1, true ]

```

please let me know how to resolve this.

Regards
Swagat

**Comment by znat** [comment]
@swagat123 Can you give more details on how you install so we can reproduce?

**Comment by swagat123** [comment]
I have used the command 
`npm install mrbot-ai/rasa-webchat`

**Comment by dliuproduction** [comment]
@swagat123 pushed a fix to master, try now

**Comment by mba1995** [comment]
```
npm ERR! path project_path\node_modules\.bin\jsesc.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete  project_path\node_modules\.bin\jsesc.cmd: ..\@babel\core\node_modules\jsesc\bin\jsesc symlink target is not controlled by npm  project_path\node_modules\jsesc
npm ERR! File exists:  project_path\node_modules\.bin\jsesc.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-03-25T10_51_47_513Z-debug.log
```

When I try to install rasa-webchat package into my app, It returns this issue. Not sure what's related to and how to solve this. 
Any help would be appreciated.
