### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by fallik** [botfront/rasa-webchat#62]
Hi everyone,

I just tried to use the webchat just as it is described [here](https://forum.rasa.com/t/connect-rasa-to-a-web-site-with-the-recommeded-plataform/4019/2) by Juste.
I can see a 500 code in Chrome's console saying `Access to XMLHttpRequest at 'http://localhost:5005/socket.io/?EIO=3&transport=polling&t=MYei2_H' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Also python is facing me with an AttributeError:
```
127.0.0.1 - - [2019-02-01 11:55:46] "GET /socket.io/?EIO=3&transport=polling&t=MYeiq3t HTTP/1.1" 500 161 0.003995
Traceback (most recent call last):
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\gevent\pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\gevent\pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\engineio\middleware.py", line 59, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\socketio\server.py", line 360, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\engineio\server.py", line 333, in handle_request
    transport, b64)
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\engineio\server.py", line 454, in _handle_connect
    s = socket.Socket(self, sid)
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\engineio\socket.py", line 17, in __init__
    self.queue = self.server.create_queue()
  File "C:\Users\niklas.fallik\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\engineio\server.py", line 430, in create_queue
    sys.modules[queue.__class__.__module__], 'Empty')
AttributeError: 'gevent._queue.JoinableQueue' object has no attribute 'Empty'
2019-02-01T10:55:53Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '57190', 'HTTP_HOST': 'localhost:5005', (hidden keys: 23)} failed with AttributeError
```
The "REMOTE_PORT" is changing once a while.

I used the html-code provided in dev/src/index.html. Chrome shows an empty page.

What am I missing?

Regards,
Nick

**Comment by dliuproduction** [comment]
Try to use https by using HTTPS=true in your npm script

**Comment by fallik** [comment]
Until now I have not done anything but cloning the repo. Can you tell me exactly where to add this?

**Comment by 123v** [comment]
Hi, is there any update on this issue? I'm facing same issue.
"Access to XMLHttpRequest at 'http://localhost:5500/socket.io/?EIO=3&transport=polling&t=MpNmxKe' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by lazurey** [comment]
I think this issue is not resolved by the commit above (https://github.com/CamaraDosDeputados/rasa-webchat/commit/b9cecd53e9ad7783d40217db4af6672c97539e73)
The commit only appended an image alt text, nothing to do with the CORS issue.

Try to add `--cors "*"` when starting the rasa socket service.

For your reference, I use the following command:
```bash
rasa run --credentials ./credentials.yml \
    -m ./models/my-model.tar.gz \
    -p 5500 \
    --cors "*"
```
